/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMeals {
  'breakfast' : string,
  'lunch' : string,
  'dinner' : string,
}
export interface GroceryItem { 'name' : string, 'totalQuantity' : string }
export type T = { 'muscle_gain' : null } |
  { 'weight_loss' : null } |
  { 'balanced_diet' : null };
export interface UserProfile { 'healthGoal' : T, 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyPlan {
  'tuesday' : DailyMeals,
  'wednesday' : DailyMeals,
  'saturday' : DailyMeals,
  'thursday' : DailyMeals,
  'sunday' : DailyMeals,
  'friday' : DailyMeals,
  'monday' : DailyMeals,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroceryList' : ActorMethod<[], Array<GroceryItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyMealPlan' : ActorMethod<[], [] | [WeeklyPlan]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'regenerateMealPlan' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserProfile' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];