/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const T = IDL.Variant({
  'muscle_gain' : IDL.Null,
  'weight_loss' : IDL.Null,
  'balanced_diet' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'healthGoal' : T,
  'displayName' : IDL.Text,
});
export const GroceryItem = IDL.Record({
  'name' : IDL.Text,
  'totalQuantity' : IDL.Text,
});
export const DailyMeals = IDL.Record({
  'breakfast' : IDL.Text,
  'lunch' : IDL.Text,
  'dinner' : IDL.Text,
});
export const WeeklyPlan = IDL.Record({
  'tuesday' : DailyMeals,
  'wednesday' : DailyMeals,
  'saturday' : DailyMeals,
  'thursday' : DailyMeals,
  'sunday' : DailyMeals,
  'friday' : DailyMeals,
  'monday' : DailyMeals,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroceryList' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyMealPlan' : IDL.Func([], [IDL.Opt(WeeklyPlan)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'regenerateMealPlan' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const T = IDL.Variant({
    'muscle_gain' : IDL.Null,
    'weight_loss' : IDL.Null,
    'balanced_diet' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'healthGoal' : T,
    'displayName' : IDL.Text,
  });
  const GroceryItem = IDL.Record({
    'name' : IDL.Text,
    'totalQuantity' : IDL.Text,
  });
  const DailyMeals = IDL.Record({
    'breakfast' : IDL.Text,
    'lunch' : IDL.Text,
    'dinner' : IDL.Text,
  });
  const WeeklyPlan = IDL.Record({
    'tuesday' : DailyMeals,
    'wednesday' : DailyMeals,
    'saturday' : DailyMeals,
    'thursday' : DailyMeals,
    'sunday' : DailyMeals,
    'friday' : DailyMeals,
    'monday' : DailyMeals,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroceryList' : IDL.Func([], [IDL.Vec(GroceryItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyMealPlan' : IDL.Func([], [IDL.Opt(WeeklyPlan)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'regenerateMealPlan' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };